pub mod auditoria;
pub mod alumnos;
pub mod bimestres;
pub mod competencias;
pub mod criterios;
pub mod evaluaciones;
pub mod exportaciones;
pub mod grados;
pub mod secciones;
pub mod sesiones;

pub use auditoria::config as auditoria_config;
pub use alumnos::config as alumnos_config;
pub use bimestres::config as bimestres_config;
pub use competencias::config as competencias_config;
pub use criterios::config as criterios_config;
pub use evaluaciones::config as evaluaciones_config;
pub use exportaciones::config as exportacion_config;
pub use grados::config as grados_config;
pub use secciones::config as secciones_config;
pub use sesiones::config as sesiones_config;